 name: Create issues
 on:
   issues:
     types:
       - labeled
 permissions: write-all
 jobs:
   create_issue:
     runs-on: ubuntu-latest
     steps:
       - name: Create issue for blazor
         if: github.event.label.name == 'blazor'
         uses: dacbd/create-issue-action@v1
         with:
           token:  ${{ secrets.GITHUB_TOKEN  }}
           owner: test-web-components
           repo: blazor
           title:  ${{ github.event.issue.title }}
           body: |
             Web Components Planning Issue: ${{ github.event.issue.html_url }}