name: Create a demo or docs issue
on:
  issues:
    types:
      - labeled
permissions:
  contents: read
  issues: write

jobs:

  create_resource_issue:

    strategy:
      matrix:
        resource: ['Demo', 'Documentation']
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create a ${{ matrix.resource }} issue
      if: ${{ github.event.label.name == format('Needs {0}', matrix.resource) }}
      uses: dblock/create-a-github-issue@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RESOURCE: ${{ matrix.resource }}
      with:
        filename: .github/RESOURCE_ISSUE_TEMPLATE.md